# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dispo.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 745)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.vue1 = PlotWidget(self.tab)
        self.vue1.setObjectName("vue1")
        self.gridLayout.addWidget(self.vue1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pg3d = GLViewWidget(self.tab_2)
        self.pg3d.setObjectName("pg3d")
        self.gridLayout_2.addWidget(self.pg3d, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtWidgets.QWidget(self.tab_3)
        self.widget.setObjectName("widget")
        self.gridLayout_4.addWidget(self.widget, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mpl = MatplotlibWidget(self.widget1)
        self.mpl.setObjectName("mpl")
        self.verticalLayout.addWidget(self.mpl)
        self.monslider = QtWidgets.QSlider(self.widget1)
        self.monslider.setMinimum(10)
        self.monslider.setMaximum(1000)
        self.monslider.setSingleStep(2)
        self.monslider.setOrientation(QtCore.Qt.Horizontal)
        self.monslider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.monslider.setTickInterval(100)
        self.monslider.setObjectName("monslider")
        self.verticalLayout.addWidget(self.monslider)
        self.mdiArea = QtWidgets.QMdiArea(self.splitter)
        self.mdiArea.setEnabled(True)
        self.mdiArea.setTabsClosable(True)
        self.mdiArea.setTabsMovable(True)
        self.mdiArea.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.mdiArea.setTabPosition(QtWidgets.QTabWidget.South)
        self.mdiArea.setObjectName("mdiArea")
        self.sw1 = QMdiSubWindow()
        self.sw1.setObjectName("sw1")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.sw1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.dial = QtWidgets.QDial(self.sw1)
        self.dial.setObjectName("dial")
        self.gridLayout_8.addWidget(self.dial, 0, 0, 1, 1)
        self.sw2 = QMdiSubWindow()
        self.sw2.setObjectName("sw2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.sw2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableView_2 = QtWidgets.QTableView(self.sw2)
        self.tableView_2.setObjectName("tableView_2")
        self.gridLayout_7.addWidget(self.tableView_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButtonCreerDisque = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonCreerDisque.setObjectName("pushButtonCreerDisque")
        self.gridLayout_5.addWidget(self.pushButtonCreerDisque, 0, 0, 1, 1)
        self.pushButtonChangerCouleur = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonChangerCouleur.setObjectName("pushButtonChangerCouleur")
        self.gridLayout_5.addWidget(self.pushButtonChangerCouleur, 1, 0, 1, 1)
        self.lineEditTexte = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEditTexte.setObjectName("lineEditTexte")
        self.gridLayout_5.addWidget(self.lineEditTexte, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 3, 0, 1, 1)
        self.dialRotation = QtWidgets.QDial(self.dockWidgetContents)
        self.dialRotation.setMinimum(-180)
        self.dialRotation.setMaximum(180)
        self.dialRotation.setWrapping(True)
        self.dialRotation.setNotchTarget(30.0)
        self.dialRotation.setNotchesVisible(True)
        self.dialRotation.setObjectName("dialRotation")
        self.gridLayout_5.addWidget(self.dialRotation, 4, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(self.dockWidgetContents_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_6.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_2)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "mpl embeded"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.sw1.setWindowTitle(_translate("MainWindow", "Sous fenêtre"))
        self.sw2.setWindowTitle(_translate("MainWindow", "Sous fenêtre"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Boîte à outils"))
        self.pushButtonCreerDisque.setText(_translate("MainWindow", "Créer disque"))
        self.pushButtonChangerCouleur.setToolTip(_translate("MainWindow", "<html><head/><body><p>hhhnmlkn<span style=\" vertical-align:super;\">mù</span></p></body></html>"))
        self.pushButtonChangerCouleur.setText(_translate("MainWindow", "Changer couleur..."))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "Dock 2"))

from matplotlibwidget import MatplotlibWidget
from pyqtgraph import PlotWidget
from pyqtgraph.opengl import GLViewWidget
from qmdisubwindow import QMdiSubWindow
